## Neural Network Introduction #2

This exercise is adapted from https://www.springboard.com/blog/beginners-guide-neural-network-in-python-scikit-learn-0-18/

We'll use SciKit Learn's built in Breast Cancer Data Set which has several features of tumors with a labeled class indicating whether the tumor was Malignant or Benign. We will try to create a neural network model that can take in these features and attempt to predict malignant or benign labels for tumors it has not seen before. Let's go ahead and start by getting the data!

In [2]:
# from sklearn.datasets import load_breast_cancer
# cancer2 = load_breast_cancer()

import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

cancer2 = load_breast_cancer()
df_cancer2 = pd.DataFrame(cancer2['data'], columns=cancer2['feature_names'])
df_cancer2['target'] = cancer2['target']


In [4]:
cancer2

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

Check out the dataframe - what are the first few rows of data?

In [3]:
# find out the attributes in the dataset
df_cancer2.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [5]:
# find out the total instances and number of features
cancer2['data'].shape

(569, 30)

In [9]:
# find out the total instances and number of features
# cancer['data'].shape
#cancer2.drop(columns=['id'], inplace=True)
#cancer2.dropna(inplace=True)
#Y=cancer2.pop('diagnosis')

In [ ]:
# use describe to find out more about the data


**Q:** what can you say about this dataset?

Now, set up the data (x) and labels (y)


In [11]:

dataset = df_cancer2.values
X = dataset[:,:-1].astype(float)
Y = dataset[:,-1]


#### Train Test Split
 
Let's split our data into training and testing sets, this is done easily with SciKit Learn's train_test_split function from model_selection:

In [15]:
from sklearn.model_selection import train_test_split


#X_train, X_test, y_train, y_test = train_test_split(X, Y, stratify=Y,random_state=1)
#clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)
#clf.predict_proba(X_test[:1])
#clf.predict(X_test[:5, :])
#clf.score(X_test, y_test)

0.9370629370629371

#### Data Preprocessing
 
The neural network may have difficulty converging before the maximum number of iterations allowed if the data is not normalized. Multi-layer Perceptron is sensitive to feature scaling, so it is highly recommended to scale your data. Note that you must apply the same scaling to the test set for meaningful results. There are a lot of different methods for normalization of data, we will use the built-in StandardScaler for standardization.

In [21]:
# Import the StandardScalar library
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit only to the training data
scaler.fit(X_train)


StandardScaler()

In [22]:
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)


#### Training the model
 
Now it is time to train our model. SciKit Learn makes this incredibly easy, by using estimator objects. In this case we will import our estimator (the Multi-Layer Perceptron Classifier model) from the neural_network library of SciKit-Learn!

In [23]:
from sklearn.neural_network import MLPClassifier



Next we create an instance of the model, there are a lot of parameters you can choose to define and customize here, we will only define the hidden_layer_sizes. For this parameter you pass in a tuple consisting of the number of neurons you want at each layer, where the nth entry in the tuple represents the number of neurons in the nth layer of the MLP model. There are many ways to choose these numbers, but for simplicity we will choose 3 layers with the same number of neurons as there are features in our data set:

In [24]:
# create a Multilayerperceptron classifier and call it mlp
#clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)
mlp = MLPClassifier(hidden_layer_sizes=(30,30,30)).fit(X_train, y_train)

Now that the model has been made we can fit the training data to our model, remember that this data has already been processed and scaled:

**Q:** What do you see in the output? What does it tell you?

#### Predictions and Evaluation
 
Now that we have a model it is time to use it to get predictions! We can do this simply with the predict() method off of our fitted model:

In [25]:
predictions = mlp.predict(X_test)

Now we can use SciKit-Learn's built in metrics such as a classification report and confusion matrix to evaluate how well our model performed:

In [26]:
predictions

array([0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
       0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 1., 0., 0., 1.])

In [28]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[48  5]
 [ 2 88]]


In [29]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.96      0.91      0.93        53
         1.0       0.95      0.98      0.96        90

    accuracy                           0.95       143
   macro avg       0.95      0.94      0.95       143
weighted avg       0.95      0.95      0.95       143



**Q:** what conclusion can you make from the confusion matrix?

#### Weights and biases

The downside however to using a Multi-Layer Preceptron model is how difficult it is to interpret the model itself. The weights and biases won't be easily interpretable in relation to which features are important to the model itself.

To extract the MLP weights and biases after training your model, you use its public attributes coefs_ and intercepts_.

In [30]:
# Print the coefficient values and interpret it
mlp.coefs_

[array([[-8.58124767e-02,  4.69684743e-02, -1.92790918e-01,
         -2.61046177e-01,  1.09036607e-01,  1.30770619e-01,
          4.00584524e-01,  3.48531980e-01,  1.95260654e-01,
         -1.39493196e-01, -3.10109250e-01, -1.84359784e-02,
         -1.32577307e-01,  1.14752767e-01,  2.54321314e-02,
         -1.00189746e-01, -2.94795368e-01,  5.63493695e-02,
          2.94368366e-01, -3.45728968e-01,  2.55506425e-01,
         -1.56830746e-02,  2.78717864e-01, -4.51754639e-02,
         -7.60722376e-02, -2.06177423e-01,  1.13657474e-01,
         -2.93852916e-01,  3.89261131e-01,  7.26142301e-02],
        [-9.97471882e-02,  2.47379364e-01,  2.11385191e-01,
          2.48600005e-01,  1.35227584e-01, -3.84024979e-02,
          3.00847871e-01, -5.88453652e-02, -5.22448339e-02,
          2.53910675e-01,  8.09145979e-02,  2.71267230e-01,
         -5.39488626e-02, -1.31419742e-01,  3.20396952e-01,
          2.93805818e-01, -3.44910664e-01, -2.29171319e-02,
         -6.72785806e-02, -1.79484350e-

In [31]:
# Print the intercepts values and interpret it
mlp.intercepts_[0]

array([-0.16523167, -0.01707071, -0.05671442, -0.29715183, -0.04604005,
        0.28266629,  0.29479804,  0.37581535, -0.04481683, -0.04152138,
       -0.14372477,  0.1087413 ,  0.08447596, -0.0534514 ,  0.21144792,
       -0.15537828, -0.00733818,  0.21289224, -0.17437938, -0.07828255,
       -0.22393043,  0.33382546,  0.04823792, -0.14107715,  0.09784871,
       -0.29430172,  0.04924596,  0.32654092, -0.17977645,  0.3760902 ])

**Q:** What do you understand from the two values?

#### Additional optional tasks...

select a few known supervised techniques and compare their performance. Use 10 fold cross validation